# used for development environment setup and testing
# this script is not used in production

version: '3.1'

services:

  db:
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./database/postgres-data:/var/lib/postgresql/data
